// <auto-generated />
using System;
using Key.Du.Pay.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Key.Du.Pay.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.CentroCustoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CC_DS");

                    b.HasKey("Id");

                    b.ToTable("CentroCusto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Matricula"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mensalidade"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Material"
                        });
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.CobrancaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CodigoPagamento")
                        .HasColumnType("double precision")
                        .HasColumnName("CO_CD_PAGAMENTO");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CO_DT_VENCIMENTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CO_DS");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("CO_MT_PAGAMENTO");

                    b.Property<int>("PlanoPagamentoID")
                        .HasColumnType("integer")
                        .HasColumnName("PP_ID");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("CO_ST");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("CO_VL");

                    b.HasKey("Id");

                    b.HasIndex("PlanoPagamentoID");

                    b.ToTable("Cobranca");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.PagamentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PA_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CobrancaID")
                        .HasColumnType("integer")
                        .HasColumnName("CO_ID");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PA_DT_PAGAMENTO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("PA_VL_PAGAMENTO");

                    b.HasKey("Id");

                    b.HasIndex("CobrancaID");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.PlanoPagamentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PP_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCustoID")
                        .HasColumnType("integer")
                        .HasColumnName("CC_ID");

                    b.Property<int>("ResponsavelFinanceiroID")
                        .HasColumnType("integer")
                        .HasColumnName("RF_ID");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoID");

                    b.HasIndex("ResponsavelFinanceiroID");

                    b.ToTable("PlanoPagamento");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.ResponsavelFinanceiroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RF_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adimplente")
                        .HasColumnType("integer")
                        .HasColumnName("RF_ST_ADIMPLENCIA");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RF_DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RF_DS");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("RF_TP_USUARIO");

                    b.HasKey("Id");

                    b.ToTable("ResponsavelFinanceiro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adimplente = 1,
                            DataCadastro = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instituição de Ensino Padre Anchieta",
                            TipoUsuario = 1
                        },
                        new
                        {
                            Id = 2,
                            Adimplente = 1,
                            DataCadastro = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Escola de Educação Infantil Pinguinho de Gente",
                            TipoUsuario = 1
                        });
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.CobrancaEntity", b =>
                {
                    b.HasOne("Key.Du.Pay.DataAccess.Database.Entities.PlanoPagamentoEntity", "PlanoPagamento")
                        .WithMany("CobrancaEntities")
                        .HasForeignKey("PlanoPagamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoPagamento");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.PagamentoEntity", b =>
                {
                    b.HasOne("Key.Du.Pay.DataAccess.Database.Entities.CobrancaEntity", "Cobranca")
                        .WithMany()
                        .HasForeignKey("CobrancaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobranca");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.PlanoPagamentoEntity", b =>
                {
                    b.HasOne("Key.Du.Pay.DataAccess.Database.Entities.CentroCustoEntity", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("CentroCustoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Key.Du.Pay.DataAccess.Database.Entities.ResponsavelFinanceiroEntity", "ResponsavelFinanceiro")
                        .WithMany()
                        .HasForeignKey("ResponsavelFinanceiroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("ResponsavelFinanceiro");
                });

            modelBuilder.Entity("Key.Du.Pay.DataAccess.Database.Entities.PlanoPagamentoEntity", b =>
                {
                    b.Navigation("CobrancaEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
